# permissions for end users to view testkinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testkind-viewer-role
rules:
- apiGroups:
  - testgroup.egapm
  resources:
  - testkinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testgroup.egapm
  resources:
  - testkinds/status
  verbs:
  - get
